# Generated by Django 5.1.4 on 2024-12-28 07:34

import django.db.models.deletion
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_subaffiliate_options_alter_department_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discription', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('Consume', 'Consume'), ('Personal', 'Personal'), ('Department', 'Department'), ('Loan', 'Loan')], max_length=50)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Consume', 'Consume'), ('Personal', 'Personal'), ('Department', 'Department'), ('Loan', 'Loan')], max_length=50)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='storage.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sn', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.ImageField(blank=True, upload_to=storage.models.get_img_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('return_purpose', models.CharField(blank=True, choices=[('EndJob', 'End Job'), ('Stolen', 'Stolen'), ('NoReason', 'No Reason')], max_length=50, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Dead', 'Dead')], max_length=50, null=True)),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmportRecord', to='storage.asset')),
                ('trans_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.exportrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('return_purpose', models.CharField(blank=True, choices=[('Damaged', 'Damaged'), ('Replace', 'Replace')], max_length=50, null=True)),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ImportRecord', to='storage.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('assign_number', models.CharField(max_length=50)),
                ('assign_date', models.DateField()),
                ('notes', models.TextField()),
                ('pdf_file', models.FileField(blank=True, upload_to=storage.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('items', models.ManyToManyField(through='storage.ImportItem', to='storage.asset')),
            ],
        ),
        migrations.AddField(
            model_name='importitem',
            name='trans_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Importeditems', to='storage.importrecord'),
        ),
    ]
