# Generated by Django 5.1.4 on 2024-12-22 10:12

import django.db.models.deletion
import django.utils.timezone
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmportRecord', to='storage.asset'),
        ),
        migrations.AlterField(
            model_name='exportitem',
            name='pic',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=storage.models.get_img_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exportitem',
            name='trans_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.exportrecord'),
        ),
        migrations.AlterField(
            model_name='exportrecord',
            name='entity_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ImportRecord', to='storage.asset'),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='trans_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.importrecord'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.company'),
        ),
    ]
