# Generated by Django 5.1.4 on 2024-12-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('storage', '0002_alter_exportitem_asset_alter_exportitem_pic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
