# Generated by Django 5.1.4 on 2024-12-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_asset_options_asset_brand_en_alter_asset_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importitem',
            old_name='trans_id',
            new_name='trans',
        ),
    ]
