# Generated by Django 5.1.4 on 2024-12-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subaffiliate_options_alter_department_type_and_more'),
        ('storage', '0003_rename_trans_id_importitem_trans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importitem',
            old_name='trans',
            new_name='record',
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='assign_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
