# Generated by Django 5.1.4 on 2024-12-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_delete_affiliate_alter_importrecord_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Car', 'Car'), ('Electronic', 'Electronic'), ('Computer', 'Computer'), ('Hardware', 'Hardware'), ('Printers', 'Printers'), ('Office', 'Office'), ('Appliance', 'Appliance'), ('Electrical', 'Electrical'), ('Equipment', 'Equipment'), ('Furniture', 'Furniture'), ('Cleaner', 'Cleaner'), ('Food', 'Food'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='importrecord',
            name='items',
            field=models.ManyToManyField(through='storage.ImportItem', to='storage.asset'),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='trans_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Importeditems', to='storage.importrecord'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='storage.assettype'),
        ),
    ]
