# Generated by Django 5.1.4 on 2024-12-29 19:29

import django.db.models.deletion
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subaffiliate_options_alter_department_type_and_more'),
        ('storage', '0005_importitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='unit',
            field=models.CharField(choices=[('piece', 'قطعة'), ('box', 'عبوة'), ('set', 'طقم')], default='piece', max_length=50, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='assign_date',
            field=models.DateField(verbose_name='تاريخ التكليف'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='assign_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التكليف'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='date',
            field=models.DateField(verbose_name='تاريخ الاذن'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='items',
            field=models.ManyToManyField(through='storage.ImportItem', to='storage.asset', verbose_name='الاصناف'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=storage.models.get_pdf_upload_path, verbose_name='ملف PDF'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الاذن'),
        ),
    ]
