# Generated by Django 5.1.4 on 2024-12-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_options_alter_employee_date_employed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['-type'], 'verbose_name': 'الجهة', 'verbose_name_plural': 'الجهات'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'التقسيم الاداري', 'verbose_name_plural': 'التقسيمات الادارية'},
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='association',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='type',
            field=models.CharField(choices=[('Sub', 'جهة تابعة'), ('Ministry', 'وزارة او هيئة'), ('Department', 'ادارة'), ('Office', 'مكتب')], default=1, max_length=50, verbose_name='نوع الجهة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('GM', 'المدير العام'), ('Department', 'ادارة'), ('Office', 'مكتب'), ('Section', 'قسم')], max_length=50, verbose_name='النوع'),
        ),
    ]
