# Generated by Django 5.1.4 on 2024-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_department_alter_affiliate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان'),
            preserve_default=False,
        ),
    ]
