# Generated by Django 5.1.4 on 2024-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_affiliate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('Department', 'ادارة'), ('Office', 'مكتب'), ('Section', 'قسم')], max_length=50, verbose_name='نوع التقسيم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_employed',
            field=models.DateField(verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('GM', 'المدير العام'), ('dept_manager', 'مدير ادارة'), ('offc_manager', 'مدير مكتب'), ('sect_manager', 'رئيس قسم'), ('unit_manager', 'رئيس وحدة'), ('employee', 'موظف'), ('financer', 'مراقب مالي')], max_length=50, verbose_name='المسمى الوظيفي'),
        ),
    ]
