# Generated by Django 5.1.4 on 2024-12-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_department_type_alter_employee_date_employed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['-type'], 'verbose_name': 'الجهة', 'verbose_name_plural': 'الجهات الاخرى'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='الادارة/المكتب'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('GM', 'المدير العام'), ('dept_manager', 'مدير ادارة'), ('offc_manager', 'مدير مكتب'), ('sect_manager', 'رئيس قسم'), ('unit_manager', 'رئيس وحدة'), ('employee', 'موظف'), ('financer', 'مراقب مالي')], max_length=50, verbose_name='الوظيفة'),
        ),
    ]
