# Generated by Django 5.1.4 on 2024-12-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_affiliate_options_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['-type'], 'verbose_name': 'جهة', 'verbose_name_plural': 'الجهات الاخرى'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'شركة', 'verbose_name_plural': 'الشركات'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'تقسيم اداري', 'verbose_name_plural': 'التقسيمات الادارية'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['date_employed'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف'),
        ),
    ]
