# Generated by Django 5.1.4 on 2024-12-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_affiliate_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='subname',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم الادارة او المكتب او القسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='subtype',
            field=models.CharField(choices=[('Department', 'ادارة'), ('Office', 'مكتب'), ('Section', 'قسم')], default=1, max_length=50, verbose_name='التقسيم الاداري'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='type',
            field=models.CharField(choices=[('Ministry', 'وزارة'), ('Authority', 'هيئة'), ('Center', 'مركز'), ('Monitor', 'مراقبة')], max_length=50, verbose_name='نوع الجهة'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الادارة او المكتب او القسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('Department', 'ادارة'), ('Office', 'مكتب'), ('Section', 'قسم')], max_length=50, verbose_name='التقسيم الاداري'),
        ),
    ]
